baseURL = "https://antiiheld.de"
disableKinds = ["RSS", "sitemap"]
languageCode = "de-DE"
timezone = "Europe/Berlin"
paginate = 3
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
theme = "winston"
themesDir = "themes"
title = "Armin´s Blog"

[params]
addFrame = true
baseColor = "#ffffff"
baseOffsetColor = "#eaeaea"
headingColor = "#1C1C1C"
highlightColor = "#1C1C1C"
textColor = "#1C1C1C"

[markup.goldmark.renderer]
hardWraps = false
unsafe = true
xhtml = false

[[menu.main]]
name = "Musikgedöns"
url = "/musik/"
weight = 3

[[menu.main]]
name = "Zeichnungen"
url = "/zeichnungen/"
weight = 2

[[menu.main]]
name = "Startseite"
url = "/"
weight = 1

[module.hugoVersion]
extended = true
min = "0.55.0"

[permalinks]
blog = "/blog/:day/:month/:year/:filename/"
musik = "/musik/:day/:month/:year/:filename/"
seiten = "/:filename/"
zeichnungen = "/zeichnungen/:day/:month/:year/:filename/"
